name: Deploy to VPS

on:
  push:
    branches:
      - main # deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Go to project directory
            cd ${{ secrets.VPS_PATH }}

            # If repo doesn't exist, clone it first
            if [ ! -d ".git" ]; then
              echo "Repository not found. Cloning..."
              git clone https://github.com/${{ github.repository }} .
            fi

            # Make sure we're on main branch
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies
            if [ -f package-lock.json ]; then
              echo "Installing dependencies using npm ci"
              npm ci
            else
              echo "Installing dependencies using npm install"
              npm install
            fi

            # Run Prisma migrations (if any)
            npx prisma migrate deploy

            # Restart or start app
            pm2 restart hris-backend || pm2 start npm --name "hris-backend" -- start
